# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: highpowerbear
email: info@highpowerbear.com
description: > # this means to ignore newlines until "baseurl:"
  Financial software solutions
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://highpowerbear.com" # the base hostname & protocol for your site
permalink: /:categories/:short_year:month:day/
url: "http://localhost:4000"
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      author: highpowerbear
      category: market
      layout: post
      default-interval: daily
      image-suffix: "png"
      tags: [bearish, bonds, bullish, candlesticks, commodity, etf, euro, gold, market, oil, resistance, stochastic, stocks, support, trendline]
symbols: {
  SPY:  "SPY - S&P 500 ETF",
  TLT:  "TLT - Treasury Bond ETF",
  GLD:  "GLD - Gold ETF",
  USO:  "USO - Crude Oil ETF",
  WTIC: "WTIC - Light Crude Oil Spot",
  FXE:  "FXE - Euro Currency ETF",
  DBA:  "DBA - Agriculture ETF",

  EURUSD: "EURUSD - Euro to US Dollar",
  AUDUSD: "AUDUSD - Australian Dollar to US Dollar",
  GBPUSD: "GBPUSD - British Pound to US Dollar",
  USDCAD: "USDCAD - US Dollar to Canadian Dollar",
  USDJPY: "USDJPY - US Dollar to Japanese Yen"
}

# Build settings
markdown: kramdown